### ISSUE TITLE
Hive Metadata ETL Error - _csv.error need to escape but no escapechar set

### ISSUE THREAD

**Issue by bleachzk** [linkedin/WhereHows#459]
2017-04-27 21:04:41 ERROR Job Launcher:83 - Traceback (most recent call last):
  File "<iostream>", line 502, in <module>
  File "<iostream>", line 360, in run
_csv.Error: need to escape, but no escapechar set

        at org.python.modules._csv._csv.Error(_csv.java:93)
        at org.python.modules._csv.PyWriter.join_append_data(PyWriter.java:245)
        at org.python.modules._csv.PyWriter.join_append(PyWriter.java:186)
        at org.python.modules._csv.PyWriter.writer_writerow(PyWriter.java:138)
        at org.python.modules._csv.PyWriter.writerow(PyWriter.java:93)
        at org.python.modules._csv.PyWriter.writer_writerows(PyWriter.java:78)
        at org.python.modules._csv.PyWriter$writer_writerows_exposer.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(PyObject.java:465)
        at org.python.pycode._pyx0.run$9(<iostream>:365)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.__call__(PyMethod.java:187)
        at org.python.pycode._pyx0.f$0(<iostream>:508)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:42)
        at metadata.etl.EtlJob.run(EtlJob.java:179)
        at metadata.etl.Launcher.main(Launcher.java:78)

WhereHows branch：master
python version：2.6.6

**Comment by alyiwang** [comment]
Hi @bleachzk , thanks for raising this issue. Actually we have a fix for HIVE ETL issues including this in Linkedin branch. Will cherry-pick to master branch ASAP.

**Comment by alyiwang** [comment]
Fixed in #472

**Comment by bleachzk** [comment]
@alyiwang thanks，there is still a problem running HiveLoad.py : 
2017-05-04 14:16:49 ERROR HiveLoad[274]:-2 - Communications link failure

**Comment by alyiwang** [comment]
Hi @bleachzk , I think this can be caused by DB connection issue or by the long DB lock time caused by some batch write command. One thing you can try is to set the job property "innodb_lock_wait_timeout" with a larger value such as 1500 for the Hive job

**Comment by bleachzk** [comment]
@alyiwang ok，thanks~~~
