### ISSUE TITLE
/api/v2/datasets points to "Not-implemented" function?

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#990]
Hi, I am switching between tag1.0.0 and master, trying to troubleshooting some bugs that might have been been fixed in master.
The most recent master version had following error:
! @774658l1c - Internal server error, for (GET) [/api/v2/datasets/count] ->
....

Caused by: java.lang.UnsupportedOperationException: Not implemented yet
	at wherehows.dao.view.DatasetViewDao.listDatasets(DatasetViewDao.java:107) ~[wherehows-dao-wherehows-dao.jar:na]
	at controllers.api.v2.Dataset.lambda$countDatasets$7(Dataset.java:105) ~[wherehows-frontend.jar:na]
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	... 6 common frames omitted

listDatasets throws NotImplemented exception in DatasetViewDao

**Comment by richardxin** [comment]
most (if not all) v2 APIs point to NotImplement functions, looks like v2 was introduced last month.

**Comment by alisaraa** [comment]
@richardxin  is there an update on this? I'm getting the same error and it seems weird.

**Comment by mars-lan** [comment]
Please use the tag v1.1.0 for now.

**Comment by alisaraa** [comment]
I rebased to v1.1.0 and I'm getting the same error:

```
wherehows-frontend_1       | 2018/03/16 01:53:37 Received 200 from http://wherehows-elasticsearch:9200
wherehows-frontend_1       | NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
wherehows-frontend_1       | 2018-03-16 01:53:46 INFO  p.a.Play:97 - Application started (Prod)
wherehows-frontend_1       | 2018-03-16 01:53:47 INFO  p.c.s.NettyServer:165 - Listening for HTTP on /0.0.0.0:9000
wherehows-backend_1        | 2018-03-16 01:53:50 INFO  application:129 - ETL job (jobName:REDSHIFT_METADATA_ETL, whEtlExecId:48) finished
wherehows-frontend_1       | 2018-03-16 01:54:02 INFO  application:81 - Creating DAO factory: wherehows.dao.DaoFactory
wherehows-frontend_1       | 2018-03-16 01:54:03 ERROR application:177 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-03-16 01:54:06 ERROR application:216 - 
wherehows-frontend_1       | 
wherehows-frontend_1       | ! @77a59p9hg - Internal server error, for (GET) [/api/v2/datasets/count] ->
wherehows-frontend_1       |  
wherehows-frontend_1       | play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Not implemented yet]
wherehows-frontend_1       | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | Caused by: java.lang.UnsupportedOperationException: Not implemented yet
wherehows-frontend_1       | 	at wherehows.dao.view.DatasetViewDao.listDatasets(DatasetViewDao.java:107) ~[wherehows-dao-wherehows-dao.jar:na]
wherehows-frontend_1       | 	at controllers.api.v2.Dataset.lambda$countDatasets$7(Dataset.java:123) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	... 7 common frames omitted
wherehows-frontend_1       | 2018-03-16 01:54:06 ERROR application:216 - 
wherehows-frontend_1       | 
wherehows-frontend_1       | ! @77a59p9hg - Internal server error, for (GET) [/api/v2/datasets?start=0] ->
wherehows-frontend_1       |  
wherehows-frontend_1       | play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Not implemented yet]
wherehows-frontend_1       | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | Caused by: java.lang.UnsupportedOperationException: Not implemented yet
wherehows-frontend_1       | 	at wherehows.dao.view.DatasetViewDao.listDatasets(DatasetViewDao.java:107) ~[wherehows-dao-wherehows-dao.jar:na]
wherehows-frontend_1       | 	at controllers.api.v2.Dataset.lambda$listDatasets$5(Dataset.java:113) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	... 7 common frames omitted
wherehows-frontend_1       | 2018-03-16 01:54:06 ERROR application:216 - 
wherehows-frontend_1       | 
wherehows-frontend_1       | ! @77a59p9ha - Internal server error, for (GET) [/api/v2/platforms] ->
wherehows-frontend_1       |  
wherehows-frontend_1       | play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Operation not implemented]
wherehows-frontend_1       | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | Caused by: java.lang.UnsupportedOperationException: Operation not implemented
wherehows-frontend_1       | 	at wherehows.dao.view.DataTypesViewDao.getAllPlatforms(DataTypesViewDao.java:38) ~[wherehows-dao-wherehows-dao.jar:na]
wherehows-frontend_1       | 	at controllers.api.v2.Dataset.lambda$listSegments$1(Dataset.java:84) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	... 7 common frames omitted
```

**Comment by richardxin** [comment]
@alisaraa this exception should be fixed with tag v1.1.0

**Comment by richardxin** [comment]
Well, I take my last msg back, I still see "Not Implemented" error on some other pages.


2018-03-16 23:59:08 ERROR application:993 - Fetch compliance suggestion Error:
java.lang.UnsupportedOperationException: Compliance Suggestion not implemented.
	at wherehows.dao.table.DatasetComplianceDao.findComplianceSuggestionByUrn(DatasetComplianceDao.java:140) ~[wherehows-dao-wherehows-dao.jar:na]
	at controllers.api.v1.Dataset.getDatasetSuggestedCompliance(Dataset.java:985) [wherehows-frontend.jar:na]
	at controllers.api.v1.Dataset.getDatasetSuggestedCompliance(Dataset.java:971) [wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$76$$anonfun$apply$76.apply(Routes.scala:3240) [wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$76$$anonfun$apply$76.apply(Routes.scala:3240) [wherehows-frontend.jar:na]
	at play.core.routing.HandlerInvokerFactory$$anon$5.resultCall(HandlerInvoker.scala:139) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.JavaAction.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.Option.map(Option.scala:145) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
2018-03-16 23:59:08 ERROR application:916 - Fetch compliance Error:
javax.persistence.NoResultException: No entity found for query
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1446) ~[org.hibernate-hibernate-core-5.2.5.Final.jar:5.2.5.Final]
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:107) ~[org.hibernate-hibernate-core-5.2.5.Final.jar:5.2.5.Final]
	at wherehows.dao.table.BaseDao.findBy(BaseDao.java:81) ~[wherehows-dao-wherehows-dao.jar:na]
	at wherehows.dao.table.DatasetComplianceDao.findComplianceById(DatasetComplianceDao.java:52) ~[wherehows-dao-wherehows-dao.jar:na]
	at wherehows.dao.table.DatasetComplianceDao.getDatasetComplianceByDatasetId(DatasetComplianceDao.java:57) ~[wherehows-dao-wherehows-dao.jar:na]
	at controllers.api.v1.Dataset.getDatasetCompliance(Dataset.java:908) ~[wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$74$$anonfun$apply$74.apply(Routes.scala:3228) [wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$74$$anonfun$apply$74.apply(Routes.scala:3228) [wherehows-frontend.jar:na]
	at play.core.routing.HandlerInvokerFactory$$anon$5.resultCall(HandlerInvoker.scala:139) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.JavaAction.apply(JavaAction.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.Option.map(Option.scala:145) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
2018-03-16 23:59:09 ERROR application:216 -

! @77ac1oinc - Internal server error, for (GET) [/api/v2/list/complianceDataTypes] ->

play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Operation not implemented]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
Caused by: java.lang.UnsupportedOperationException: Operation not implemented
	at wherehows.dao.view.DataTypesViewDao.getAllComplianceDataTypes(DataTypesViewDao.java:31) ~[wherehows-dao-wherehows-dao.jar:na]
	at controllers.api.v2.Dataset.lambda$getComplianceDataTypes$9(Dataset.java:115) ~[wherehows-frontend.jar:na]
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
	... 6 common frames omitted
2018-03-16 23:59:09 ERROR application:216 -

**Comment by alisaraa** [comment]
Yeah I’m still getting it but I don’t see anything it changes in the webpage so I’m not worried unless you are.
I did notice the columns definition was removed from v1.1.0.

**Comment by richardxin** [comment]
it was pointed to an "not implemented" function at
https://github.com/linkedin/WhereHows/blob/v1.1.0/wherehows-dao/src/main/java/wherehows/dao/table/DatasetComplianceDao.java#L140

**Comment by richardxin** [comment]
this is a duplicate of issue #1048

**Comment by richardxin** [comment]
Close this as duplicate of 1048
